name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # As to be >= 1.22 because of for loop variable capturing

      - name: Install dependencies
        run: go mod tidy

      - name: Run normal tests
        run: go test -v ./... 

      - name: Run forwarding tests
        continue-on-error: true
        run: go test -ldflags="-X 'bangs/pkg/bangs.runForwardingTests=true'" -v ./...
